---
version: "3.8"
services:
  movies:
    image: arjun6074/netflix:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: arjun6074/netflix:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
